### ISSUE TITLE
Ghidra is a software reverse engineering (SRE) framework created and maintained by the National Security Agency Research Directorate. This framework includes a suite of full-featured, high-end software analysis tools that enable users to analyze compiled code on a variety of platforms including Windows, macOS, and Linux.

### ISSUE THREAD

**Issue by franksupercell** [illkasupercell/titanengine#3]
Ghidra is a software reverse engineering (SRE) framework created and maintained by the National Security Agency Research Directorate. This framework includes a suite of full-featured, high-end software analysis tools that enable users to analyze compiled code on a variety of platforms including Windows, macOS, and Linux.

**Comment by illkasupercell** [comment]
слыш френк ты нахуя бравл старс выложил с дебаг символами
