### ISSUE TITLE
хуесос ебанный 

### ISSUE THREAD

**Issue by SavokBS** [illkasupercell/titanengine#4]
ты че там про хеона сказал сука ебанная я твой бравл старс ебанный заддошу блять пидор старый блять

**Comment by iamnalinor** [comment]
> ты че там про хеона сказал сука ебанная я твой бравл старс ебанный заддошу блять пидор старый блять

хуен лох

**Comment by ghost** [comment]
> ты че там про хеона сказал сука ебанная я твой бравл старс ебанный заддошу блять пидор старый блять

бедная сосалка хуена

**Comment by franksupercell** [comment]
> ты че там про хеона сказал сука ебанная я твой бравл старс ебанный заддошу блять пидор старый блять

ты чё

**Comment by illkasupercell** [comment]
ебать ты подсос хуёнчика шлюха я ваши обходы ебал в жопу ты чмошник и шлюха и пидор и мать твоя сдохла
